# Generated by Django 2.0 on 2019-12-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.TextField()),
                ('corect', models.TextField()),
                ('incorrect_1', models.TextField()),
                ('incorrect_2', models.TextField()),
                ('incorrect_3', models.TextField()),
                ('number_correct', models.IntegerField()),
            ],
        ),
    ]
