# Generated by Django 2.0 on 2019-12-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='corect',
            new_name='correct_Ans',
        ),
    ]
